export const SELECT_PRODUCT_DETAILS = 'SELECT_PRODUCT';
export const SELECT_PRODUCT_COMPARE = 'SELECT_COMPARE';
export const SELECT_PRODUCT_CART = 'SELECT_CART';

export const OPEN_CART = "OPEN_CART";
export const CLOSE_CART = "CLOSE_CART";

export const OPEN_COMPARE = "OPEN_COMPARE";
export const CLOSE_COMPARE = "CLOSE_COMPARE";

export const CLOSE_PRODUCT_DETAILS = 'HIDE_PRODUCT';
